DbShoppingMallProject/Controllers/ManageRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DbShoppingMallProject.Data;
using DbShoppingMallProject.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DbShoppingMallProject.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class ManageRoleController : Controller
    {
        
        private ApplicationDbContext db { get; set; }
        public readonly RoleManager<IdentityRole> manager;
        public readonly UserManager<ApplicationUser> userManager;
        public ManageRoleController(RoleManager<IdentityRole> role, UserManager<ApplicationUser> userManager)
        {
            this.manager = role;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(manager.Roles.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(RoleVm vm)
        {
            IdentityRole identityRole = new IdentityRole
            {
                Name = vm.Name,
            };
            if (ModelState.IsValid)
            {
                IdentityResult result = await manager.CreateAsync(identityRole);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                if (result.Errors.Count() > 0)
                {
                    foreach (var s in result.Errors)
                    {
                        ModelState.AddModelError("", s.ToString());
                    }
                }
            }
            return View(identityRole);
        }


        public IActionResult AssignRole()
        {
            try
            {
                var list = userManager.Users.ToList();
                ViewBag.Userlist = new SelectList(list, "Id", "UserName");
                ViewBag.Rolelist = new SelectList(manager.Roles, "Name", "Name");

            }
            catch (Exception ex)
            {
                ViewBag.result = ex.Message;
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(string Userlist, string Rolelist)
        {
            try
            {
                var list = userManager.Users.ToList();
                ViewBag.Userlist = new SelectList(list, "Id", "UserName");
                ViewBag.Rolelist = new SelectList(manager.Roles, "Name", "Name");
                var user = await userManager.FindByIdAsync(Userlist);
                IdentityResult result = await userManager.AddToRoleAsync(user, Rolelist);
                if (result.Succeeded)
                {
                    ViewBag.result = user.UserName + "successfully assign" + Rolelist;
                }
                if (result.Errors.Count() > 0)
                {

                }
            }
            catch (Exception ex)
            {
                ViewBag.result = ex.Message;
            }




            return View("AssignRole");
        }


        [Authorize(Roles ="it")]
        public async Task<IActionResult> DisplayClaim()
        {
            var claimVm = new ClaimVm
            {
                Email = ""
            };
            try
            {
                var list = userManager.Users.ToList();
                ViewBag.Userlist = new SelectList(list, "UserName", "UserName");
                var allClaims = ClaimStore.GetClaims;

                var user = await userManager.FindByEmailAsync(claimVm.Email);
                if (user == null)
                {
                    foreach (var c in allClaims)
                    {
                        UserClaims userClaims = new UserClaims
                        {
                            ClaimType = c.Type,
                            Isselected = false
                        };

                        claimVm.UserClaims.Add(userClaims);
                    }
                }
                else
                {
                    var existingClaim = await userManager.GetClaimsAsync(user);
                    foreach (var c in allClaims)
                    {
                        UserClaims userClaims = new UserClaims
                        {
                            ClaimType = c.Type,
                        };
                        if (existingClaim.Any(a => a.Type == c.Type))
                        {
                            userClaims.Isselected = true;
                        }
                        claimVm.UserClaims.Add(userClaims);
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Result = ex.Message;
            }
            return View(claimVm);
        }
        [HttpPost]
        public async Task<IActionResult> DisplayClaim(ClaimVm vm, string Userlist)
        {
            var user = await userManager.FindByEmailAsync(Userlist);
            var existingClaim = await userManager.GetClaimsAsync(user);
            foreach (var c in existingClaim)
            {
                await userManager.RemoveClaimAsync(user, c);
            }
            foreach (var c in vm.UserClaims)
            {
                if (c.Isselected)
                {
                    IdentityResult result = await userManager.AddClaimAsync(user, new System.Security.Claims.Claim(c.ClaimType, c.ClaimType));
                    if (result.Succeeded)
                    {
                        ViewBag.Result = "Selected claim on" + vm.Email + " successfully assigned";
                    }
                }
            }
            return View(vm);
        }
    }
}

DbShoppingMallProject/Views/ManageRole/AssignRole.cshtml
@{
    ViewData["Title"] = "AssignRole";
}

<h2>Assign Roll to User</h2>

<div>
    @if (ViewBag.result != null)
    {

    }
</div>
<form method="post" action="AssignRole">
    <div class="row clearfix">
        <div class="col-md-4">
            <label>User</label>
            @if (ViewBag.Userlist != null)
            {
                <select asp-items="@ViewBag.Userlist" name="Userlist">
                    <option>
                        Select User name
                    </option>
                </select>
            }
        </div>
        <div class="col-md-4">
            <label>User</label>
            @if (ViewBag.Rolelist != null)
            {
                <select asp-items="@ViewBag.Rolelist" name="Rolelist">
                    <option>
                        Select Role name
                    </option>
                </select>
            }
        </div>
        <div>
            <input type="submit" value="Assign" />
        </div>
    </div>
</form>

DbShoppingMallProject/Views/ManageRole/Create.cshtml
@model DbShoppingMallProject.ViewModel.RoleVm

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>RolesVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DbShoppingMallProject/Views/ManageRole/DisplayClaim.cshtml
@model DbShoppingMallProject.ViewModel.ClaimVm
@{
    ViewData["Title"] = "DisplayClaim";
}

<h2>DisplayClaim</h2>

<div>
    @ViewBag.Result
</div>

<form method="post" asp-action="DisplayClaim">
    <div class="panel">
        <div class="panel-heading">
            <h2>Manager User claim</h2>
        </div>
        <div class="panel-body">
            <div>
                @if (ViewBag.Userlist != null)
                {
                    <select asp-items="@ViewBag.Userlist" name="Userlist" asp-for="@Model.Email">
                        <option>
                            Select User name
                        </option>
                    </select>
                }
            </div>
            <div>
                @for (int i = 0; i < Model.UserClaims.Count; i++)
                {
                    <input asp-for="@Model.UserClaims[i].ClaimType" hidden />
                    <input asp-for="@Model.UserClaims[i].Isselected" />
                    <label asp-for="@Model.UserClaims[i].Isselected">
                        @Model.UserClaims[i].ClaimType
                    </label>
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Assign" />
        </div>
    </div>
</form>

DbShoppingMallProject/Views/ManageRole/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Index";
}



@Html.ActionLink("Create", "Create", "ManageRole")
<h2>Role List</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
        </tr>
    }

</table>