DbShoppingMallProject/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DbShoppingMallProject.Data;
using DbShoppingMallProject.Models;
using DbShoppingMallProject.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DbShoppingMallProject.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IHostingEnvironment ihost;

        public CategoriesController(ApplicationDbContext db, IHostingEnvironment host)
        {
            this.db = db;
            this.ihost = host;
        }


        public IActionResult Index()
        {
            return View(db.Categories.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            ViewBag.CatId = new SelectList(db.Categories.ToList(), "Id", "Name");
            List<CatStallVm> data = new List<CatStallVm>();
            foreach(Category category in db.Categories)
            {
                data.Add(new CatStallVm
                {
                    Category = category.Name,
                    Description = category.Description,
                    Stalls = db.Stalls.Where(p => p.CatId == category.Id).ToList()
                });
            }
            return View(data);
        }
        public IActionResult Update(IFormCollection data)
        {
            Stall s = new Stall
            {
                StallName = data["txtname"],
                StallVolume = int.Parse(data["txtvolum"]),
                Level = (Level)Enum.Parse(typeof(Level), data["txtLevel"]),
                Id = int.Parse(data["txtId"]),
                CatId=int.Parse(data["txtcat"])
            };
            db.Entry(s).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("GetAll");

        }
    }
}

DbShoppingMallProject/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DbShoppingMallProject.Data;
using DbShoppingMallProject.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DbShoppingMallProject.Controllers
{
    public class ProfileController : Controller
    {
        private UserManager<ApplicationUser> userManager;
        private readonly IHostingEnvironment hosting;

        public ProfileController(UserManager<ApplicationUser> userManager, IHostingEnvironment hosting)
        {
            this.userManager = userManager;
            this.hosting = hosting;
        }
        public IActionResult Index()
        {
            var userID = userManager.GetUserId(HttpContext.User);
            ApplicationUser user = userManager.FindByIdAsync(userID).Result;

            return View(user);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var userID = userManager.GetUserId(HttpContext.User);
            ApplicationUser user = userManager.FindByIdAsync(userID).Result;

            var user1 = await userManager.FindByIdAsync(id);
            ProfileVm vm = new ProfileVm
            {
                Id = id,
                UserName = user.UserName,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                ImagePath = user.ImagePath,
                SecurityStamp = user.SecurityStamp

            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProfileVm vm)
        {
            try
            {
                var user1 = await userManager.FindByIdAsync(vm.Id);
                if (user1 == null)
                {
                    ViewBag.ErrorMessage = $"User with Id={vm.Id} cannot be found";
                    return View("NotFound");
                }
                else
                {
                    if (vm.Imgfile != null)
                    {
                        string ext = Path.GetExtension(vm.Imgfile.FileName).ToLower();
                        if (ext == ".jpg" || ext == ".png" || ext == ".jpeg")
                        {
                            var filename = Path.GetFileNameWithoutExtension(vm.Imgfile.FileName) + "_ "+ Guid.NewGuid() + ext;
                            var filePath = Path.Combine(hosting.WebRootPath, "images\\ProfilePic", filename);
                            using (var fileStream = new FileStream(filePath, FileMode.Create))
                            {
                                vm.Imgfile.CopyTo(fileStream);
                                user1.ImagePath = "\\images\\ProfilePic\\" + filename;
                            }
                        }
                    }
                    else
                    {
                        user1.ImagePath = vm.ImagePath;
                    }

                    user1.Id = vm.Id;
                    user1.UserName = vm.UserName;
                    user1.Email = vm.Email;
                   
                    user1.SecurityStamp = vm.SecurityStamp;
                    user1.PhoneNumber = vm.PhoneNumber;


                    IdentityResult result = await userManager.UpdateAsync(user1);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    foreach (var e in result.Errors)
                    {
                        ModelState.AddModelError("", e.Description);
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Result = ex.Message;
            }

            return View(vm);
        }
    }
}

DbShoppingMallProject/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DbShoppingMallProject.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace DbShoppingMallProject.Controllers
{
    public class ServiceController : Controller
    {
       private readonly ApplicationDbContext db;
        public ServiceController(ApplicationDbContext context)
        {
            this.db = context;
        }

        public IActionResult Index()
        {
            //var services = db.Services.Include(s => s.CompanyInfo);
            var proc = db.Services.FromSql<Services>("Sp_ServiceAllData");
            return View(proc);
        }
        public IActionResult Create()
        {
            ViewData["stallId"] = new SelectList(db.Stalls, "Id", "StallName");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Services s)
        {
            ViewData["stallId"] = new SelectList(db.Stalls, "Id", "StallName",s.StallId);
            var proc = db.Database.ExecuteSqlCommand("Sp_ServiceCreate @title={0},@descrip={1},@stallId={2}",
                s.Title,s.Description,s.StallId);
            if (proc > 0)
            {
                return RedirectToAction("Index");
            }
            return View(s);
        }
        public IActionResult Edit(int id)
        {
            ViewData["stallId"] = new SelectList(db.Stalls, "Id", "StallName",db.Services.Find(id).StallId);
            var proc = db.Services.FromSql<Services>("Sp_ServiceDetails @id={0}", id).SingleOrDefault();
            return View(proc);

        }
        [HttpPost]
        public IActionResult Edit(Services s)
        {
            ViewData["stallId"] = new SelectList(db.Stalls, "Id", "StallName",s.StallId);
            var proc = db.Database.ExecuteSqlCommand("Sp_ServiceUpdate @title={0},@descrip={1},@stallId={2},@id={3}",
                s.Title, s.Description, s.StallId,s.Id);
            if (proc > 0)
            {
                return RedirectToAction("Index");
            }
            return View(s);
            
        }
        public IActionResult Delete(int id)
        {
            

            var proc = db.Database.ExecuteSqlCommand("Sp_ServiceDelete @id={0}", id);
            if (proc > 0)
            {
                return RedirectToAction("Index"); 
            }
            return View("Index");
        }
        public IActionResult Details(int id)
        {
            var proc = db.Services.FromSql<Services>("Sp_ServiceDetails @id={0}", id).SingleOrDefault();
            return View(proc);
        }

    }
}

DbShoppingMallProject/Controllers/StallsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbShoppingMallProject.Data;
using DbShoppingMallProject.Models;

namespace DbShoppingMallProject.Controllers
{
    public class StallsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StallsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Stalls
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Stalls.Include(s => s.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Stalls/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stall = await _context.Stalls
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stall == null)
            {
                return NotFound();
            }

            return View(stall);
        }
        public IActionResult MultiCreate()
        {
            ViewData["CatId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MultiCreate(List<Stall> stalls)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.AddRange(stalls);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                return View(stalls);
            }
            return View(stalls);

        }
        // GET: Stalls/Create
        public IActionResult Create()
        {
            ViewData["CatId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: Stalls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StallNo,StallName,CatId,StallVolume,Level")] Stall stall)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stall);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "Id", "Id", stall.CatId);
            return View(stall);
        }

        // GET: Stalls/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stall = await _context.Stalls.FindAsync(id);
            if (stall == null)
            {
                return NotFound();
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "Id", "Id", stall.CatId);
            return View(stall);
        }

        // POST: Stalls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StallNo,StallName,CatId,StallVolume,Level")] Stall stall)
        {
            if (id != stall.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stall);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StallExists(stall.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "Id", "Id", stall.CatId);
            return View(stall);
        }

        // GET: Stalls/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stall = await _context.Stalls
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stall == null)
            {
                return NotFound();
            }

            return View(stall);
        }

        // POST: Stalls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stall = await _context.Stalls.FindAsync(id);
            _context.Stalls.Remove(stall);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StallExists(int id)
        {
            return _context.Stalls.Any(e => e.Id == id);
        }
    }
}

DbShoppingMallProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DbShoppingMallProject</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DbShoppingMallProject</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Service" asp-action="index">Service</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Categories" asp-action="GetAll">CatStall</a></li>
                    <li><a asp-area="" asp-controller="Categories1" asp-action="Index">Category</a></li>
                    <li><a asp-area="" asp-controller="Stalls" asp-action="Index">Stall</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Stall <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Stalls" asp-action="Index">All Stall</a></li>
                            <li><a asp-area="" asp-controller="Stalls" asp-action="MultiCreate">Multi Insert</a></li>
                            <li><a asp-area="" asp-controller="Categories1" asp-action="Index">Stall with Category</a></li>
                            <li><a asp-area="" asp-controller="Categories" asp-action="GetAll">Relational Crud</a></li>

                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-right">

                    
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Admin <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                            <li><a asp-area="" asp-controller="ManageRole" asp-action="Index">Role</a></li>
                            <li><a asp-area="" asp-controller="ManageRole" asp-action="AssignRole">Assign Role to user</a></li>
                            <li><a asp-area="" asp-controller="ManageRole" asp-action="DisplayClaim">Claim</a></li>

                        </ul>
                    </li>

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content "  >
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - DbShoppingMallProject</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>